### ISSUE TITLE
[3] Category model does not have softdelete trait

### ISSUE THREAD

**Issue by luukholleman** [Riari/laravel-forum#79]
On a plain install, you can't view a category. You get the error

```
ErrorException in Builder.php line 2071:
Call to undefined method Illuminate\Database\Query\Builder::withTrashed() 
```

The category model doesn't have a softdelete trait. Also the table forum_categories doesn't have a deleted_at field

**Comment by Riari** [comment]
It's not supposed to anymore - looks like I missed some references to it in the category API controller. Fixed in 361115b591e0dd896e57a7c644f5a66cb08ebbe1.

**Comment by luukholleman** [comment]
You missed some. You can't show a category with threads in it. 

Will give:

```
Call to undefined method Illuminate\Database\Query\Builder::withTrashed() 
(View: <path>/resources/views/vendor/forum/category/partials/list.blade.php)
```

**Comment by Riari** [comment]
The only remaining reference I found was on [line 51](https://github.com/Riari/laravel-forum/blob/6153c2f25316c36fe731756fd20ac8ac173eb9ba/src/Models/Thread.php#L51) of the thread model. Updated now.
